version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx.dockerfile
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend1
      - backend2
      - backend3

  backend1:
    build:
      context: .
      dockerfile: Dockerfile.java17.dockerfile
    environment:
      - SERVER_PORT=9999

  backend2:
    build:
      context: .
      dockerfile: Dockerfile.java17.dockerfile
    environment:
      - SERVER_PORT=9998

  backend3:
    build:
      context: .
      dockerfile: Dockerfile.java17.dockerfile
    environment:
      - SERVER_PORT=9997
